export enum AbilityType {
  // Attack:
  HeroDoubleSimpleAttack,
  HeroBasicAttack,
  HeroSimpleAttackTwoTargets,
  HeroPoisonMedium,
  HeroPoisonStrong,
  HeroPoisonWeak,
  HeroRage,
  HeroStanMedium,
  HeroStanStrong,
  HeroStanWeak,
  HeroThrowSpearow,
  // Defense:
  HeroAcceptAggression,
  HeroAttackOffset,
  HeroRemoveAggression,
  HeroResistPoisonWeak,
  HeroShieldWeak,
  HeroShieldMedium,
  HeroShieldStrong,
  // Heal:
  HeroBasicHeal,
  HeroBasicHealTwoTargets,
  HeroBasicHealThreeTargets,
  HeroHealAfterBattle,
  HeroHealPoison,
  HeroHealFromPoisonAfterBattle,
  HeroHealWithAllies,
  HeroHealMedium,
  HeroHealStrong,
  HeroHealWeak,
  // Magic:
  HeroCastDecreaseRegeneration1,
  HeroCastFireBall,
  HeroCastFlash,
  HeroCastImbecility,
  HeroCastLightningStrikes,
  HeroCastMagicAttackStanned,
  HeroCastMagicProtection,
  HeroCastSlackness,
  HeroCastSuppression,
  HeroCastTripleMagicAttack,
  HeroCastTripleStan,
  HeroCastTurningToStone,
  // Special:
  AddSecondHero,
  AddThirdHero,
  HeroHideCreature,
  HeroIncreaseHealTarget,
  HeroSacrifice,
  HeroTargetAttack,
  HeroThrowAxe,
  HeroUseBottleOfHeal,
  HeroUseBottleOfStan,
  HeroUseBottleOfPoison,
  HeroWonderHeal,
  // Monsters:
  MonsterAddonSunLazy,
  MonsterAttackEqualsTargetArmor,
  MonsterBasicAttack,
  MonsterBasicAttackAnotherTarget,
  MonsterBasicAttackTwoTargets,
  MonsterBasicAttackWithRandomEnemyTarget,
  MonsterBasicHeal,
  MonsterDoubleBasicAttack,
  MonsterDoubleThrowSpearow,
  MonsterHeadAttackWithStan,
  MonsterMagicAttack3,
  MonsterBasicAttackWithThrow,
  MonsterShieldAttack,
  MonsterThrowSpearow1,
  MonsterThrowSpearow4,
}
