export enum SearchEventType {
  ThrowDice,
  Nothing,
  Smth,
  AllHeroes,
  SeparateHeroes,
  CheckHero,
  SelectedHero,
  NotSelectedHero,
  FoundTreasure,
  FoundSourceHolyWater,
  FoundSecretPath,
  LossMoney,
  LossHitpoints,
  LossThings,
  ExistsTrap,
  SearchIsCompleted,
}
