import { AbilityType } from '@app/shared/enums';
import { AbilitySettings } from '@app/shared/models';

export const ShopAbilitiesMagic: AbilitySettings[] = [
  {
    type: AbilityType.HeroCastDecreaseRegeneration1,
    name: 'Ослабление регенерации.',
    description: 'Снижение регенерации на 1 до конца боя',
    image: 'assets/img/abilities/decrease-regeneration-1.jpg',
    cost: 300,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    countTarget: 1,
  },
  {
    type: AbilityType.HeroCastSlackness,
    name: 'Вялость',
    description: 'На следующий ход урон цели снижается на 2',
    image: 'assets/img/abilities/sadness.jpg',
    cost: 200,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    countTarget: 1,
  },
  {
    type: AbilityType.HeroCastFlash,
    name: 'Вспышка',
    description: 'Урон 2 + "бросок"',
    image: 'assets/img/abilities/flash.jpg',
    cost: 800,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    isMagicAttack: true,
    countTarget: 1,
  },
  {
    type: AbilityType.HeroCastFireBall,
    name: 'Огненный шар',
    description: 'Урон 5 + "бросок"',
    image: 'assets/img/abilities/fire-ball.jpg',
    cost: 1500,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    isMagicAttack: true,
    countTarget: 1,
  },
  {
    type: AbilityType.HeroCastTripleMagicAttack,
    name: 'Кара стихий',
    description: 'Урон 3 * "бросок", герой теряет 4 жизни',
    image: 'assets/img/abilities/triple-magic-attack.jpg',
    cost: 1700,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    isMagicAttack: true,
    countTarget: 1,
  },
  {
    type: AbilityType.HeroCastTurningToStone,
    name: 'Окаменение',
    description: 'Маг теряет 4 жизни и не получает урон до следующего хода',
    image: 'assets/img/abilities/turning-to-stone.jpg',
    cost: 600,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    countTarget: null,
  },
  {
    type: AbilityType.HeroCastMagicProtection,
    name: 'Магический щит',
    description: 'Цель получает защиту от магических атак до конца раунда',
    image: 'assets/img/abilities/magic-protection.jpg',
    cost: 200,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    countTarget: 1,
  },
  {
    type: AbilityType.HeroCastLightningStrikes,
    name: 'Удары молний',
    description: 'Урон равен "броску", до 3х целей',
    image: 'assets/img/abilities/lightning-strikes.jpg',
    cost: 2000,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    isMagicAttack: true,
    countTarget: 3,
  },
  {
    type: AbilityType.HeroCastTripleStan,
    name: 'Оглушение троих',
    description: 'Шанс 50%, до 3х целей',
    image: 'assets/img/abilities/triple-stan.jpg',
    cost: 1400,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    countTarget: 3,
  },
  {
    type: AbilityType.HeroCastMagicAttackStanned,
    name: 'Леденящий поток',
    description: 'Урон равен "бросок", по оглушенным двойной урон и оглушение снимается',
    image: 'assets/img/abilities/magic-attack-stanned.jpg',
    cost: 600,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    isMagicAttack: true,
    countTarget: 1,
  },
  {
    type: AbilityType.HeroCastSuppression,
    name: 'Подавление',
    description: 'Цель получает двойной урон от атак до конца раунда',
    image: 'assets/img/abilities/suppression.jpg',
    cost: 700,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    countTarget: 1,
  },
  {
    type: AbilityType.HeroCastImbecility,
    name: 'Скудоумие',
    description: 'Шанс 50%, в следующий ход цель атакует случайное существо',
    image: 'assets/img/abilities/imbecility.jpg',
    cost: 700,
    maxUseCount: null,
    isImmediateAction: false,
    isAddonAction: false,
    countTarget: 1,
  },
];
