import { AbilityType } from '@app/shared/enums';
import { AbilitySettings } from '@app/shared/models';

export const ShopAbilitiesAttack: AbilitySettings[] = [
  {
    type: AbilityType.HeroPoisonWeak,
    name: 'Слабый яд',
    description: 'Шанс отравления цели 1 из 6, урон 2',
    image: 'assets/img/abilities/poison-attack.jpg',
    cost: 300,
    maxUseCount: null,
    isImmediateAction: true,
    isPassiveAction: true,
    isAddonAction: false,
    countTarget: null,
  },
  {
    type: AbilityType.HeroPoisonMedium,
    name: 'Средний яд',
    description: 'Шанс отравления цели 1 из 3, урон 2',
    image: 'assets/img/abilities/poison-attack.jpg',
    cost: 500,
    maxUseCount: null,
    isImmediateAction: true,
    isPassiveAction: true,
    isAddonAction: false,
    countTarget: null,
  },
  {
    type: AbilityType.HeroPoisonStrong,
    name: 'Сильный яд',
    description: 'Шанс отравления цели 1 из 2, урон 3',
    image: 'assets/img/abilities/poison-attack.jpg',
    cost: 900,
    maxUseCount: null,
    isImmediateAction: true,
    isPassiveAction: true,
    isAddonAction: false,
    countTarget: null,
  },
  {
    type: AbilityType.HeroStanWeak,
    name: 'Слабое оглушение',
    description: 'Шанс оглушения цели 1 из 6 (пропускает ход)',
    image: 'assets/img/abilities/stan-weak.jpg',
    cost: 200,
    maxUseCount: null,
    isImmediateAction: true,
    isPassiveAction: true,
    isAddonAction: false,
    countTarget: null,
  },
  {
    type: AbilityType.HeroStanMedium,
    name: 'Среднее оглушение',
    description: 'Шанс оглушения цели 1 из 3 (пропускает ход)"',
    image: 'assets/img/abilities/stan-medium.jpg',
    cost: 500,
    maxUseCount: null,
    isImmediateAction: true,
    isPassiveAction: true,
    isAddonAction: false,
    countTarget: null,
  },
  {
    type: AbilityType.HeroStanStrong,
    name: 'Сильное оглушение',
    description: 'Шанс оглушения цели 1 из 2 (пропускает ход)"',
    image: 'assets/img/abilities/stan-strong.jpg',
    cost: 800,
    maxUseCount: null,
    isImmediateAction: true,
    isPassiveAction: true,
    isAddonAction: false,
    countTarget: null,
  },
  {
    type: AbilityType.HeroRage,
    name: 'Ярость',
    description: 'При выпадании 6 во время атаки - удвоение урона',
    image: 'assets/img/abilities/rage.jpg',
    cost: 300,
    maxUseCount: null,
    isImmediateAction: true,
    isPassiveAction: true,
    isAddonAction: false,
    countTarget: null,
  },
  {
    type: AbilityType.HeroThrowSpearow,
    name: 'Метание сулицы',
    description: 'Атака противника на 1 + "бросок", 1 раз в ход (2 раза за бой)',
    image: 'assets/img/abilities/throw-spearow.jpg',
    cost: 200,
    maxUseCount: 2,
    isImmediateAction: false,
    isAddonAction: true,
    countTarget: 1,
  },
];
