import { EffectType } from '@enums';
import { EffectSettings } from '@models';

export const Effects: EffectSettings[] = [
  {
    effectType: EffectType.AttackOffset,
    name: 'Смещение атаки',
    image: 'assets/img/effects/attack-offset.jpg.jpg',
    description: 'При получении удара в голову, атака переходит в другую часть тела (1 раз за бой)',
  },
  {
    effectType: EffectType.AttackWithBlockHeal,
    name: 'Ядовитые чары',
    image: 'assets/img/effects/attack-with-block-heal.jpg',
    description: 'Атакованный не может исцеляться до конца хода',
  },
  {
    effectType: EffectType.AttackWithCourse,
    name: 'Проклятая атака',
    image: 'assets/img/effects/attack-with-course.jpg',
    description: 'Цель наносит минимальный урон',
  },
  {
    effectType: EffectType.AttackWithIgnoringArmor,
    name: 'Крушащий удар',
    image: 'assets/img/effects/attack-with-ignoring-armor.jpg',
    description: 'Игнорирует броню цели',
  },
  {
    effectType: EffectType.AttackWithIgnoringShield,
    name: 'Игнорирование щита',
    image: 'assets/img/effects/attack-with-ignoring-shield.jpg',
    description: 'Цель не получает броню за щит',
  },
  {
    effectType: EffectType.AttackWithPoisonWeak1,
    name: 'Слабый яд',
    image: 'assets/img/effects/attack-with-poison.jpg',
    description: 'Шанс 1 из 6, урон 1',
  },
  {
    effectType: EffectType.AttackWithPoisonWeak2,
    name: 'Слабый яд',
    image: 'assets/img/effects/attack-with-poison.jpg',
    description: 'Шанс отравления цели 1 из 6, урон 2',
  },
  {
    effectType: EffectType.AttackWithPoisonMedium2,
    name: 'Средний яд',
    image: 'assets/img/effects/attack-with-poison.jpg',
    description: 'Шанс отравления цели 1 из 3, урон 2',
  },
  {
    effectType: EffectType.AttackWithPoisonStrong3,
    name: 'Сильный яд',
    image: 'assets/img/effects/attack-with-poison.jpg',
    description: 'Шанс отравления цели 1 из 2, урон 3',
  },
  {
    effectType: EffectType.AttackWithStanWeak,
    name: 'Слабое оглушение',
    image: 'assets/img/effects/attack-with-stan-weak.jpg',
    description: 'Шанс оглушения цели 1 из 6',
  },
  {
    effectType: EffectType.AttackWithStanMedium,
    name: 'Среднее оглушение',
    image: 'assets/img/effects/attack-with-stan-medium.jpg',
    description: 'Шанс оглушения цели 1 из 3',
  },
  {
    effectType: EffectType.AttackWithStanStrong,
    name: 'Сильное оглушение',
    image: 'assets/img/effects/attack-with-stan-strong.jpg',
    description: 'Шанс оглушения цели 1 из 2',
  },
  {
    effectType: EffectType.BlockDamage,
    name: 'Окаменение',
    image: 'assets/img/effects/block-damage.jpg',
    description: 'Не получает повреждений',
  },
  {
    effectType: EffectType.BlockHeal,
    name: 'Проказа',
    image: 'assets/img/effects/block-heal.jpg',
    description: 'Не подвержен лечению до конца хода',
  },
  {
    effectType: EffectType.BreakingChests,
    name: 'Умелый взломщик',
    image: 'assets/img/effects/todo.jpg',
    description: '+1 к вскрытию сундуков',
  },
  {
    effectType: EffectType.Course,
    name: 'Проклятие',
    image: 'assets/img/effects/course.jpg',
    description: 'При атаке наносится минимальный урон (бросок равен 1).',
  },
  {
    effectType: EffectType.CreatureWithoutBody,
    name: 'Нет тела',
    image: 'assets/img/effects/creature-without-body.jpg',
    description: '',
  },
  {
    effectType: EffectType.CreatureWithoutHands,
    name: 'Нет рук',
    image: 'assets/img/effects/creature-without-hands.jpg',
    description: '',
  },
  {
    effectType: EffectType.CreatureWithoutHead,
    name: 'Нет головы',
    image: 'assets/img/effects/creature-without-head.jpg',
    description: '',
  },
  {
    effectType: EffectType.CreatureWithoutLegs,
    name: 'Нет ног',
    image: 'assets/img/effects/creature-without-legs.jpg',
    description: '',
  },
  {
    effectType: EffectType.Destructible13,
    name: 'Разрушимость',
    image: 'assets/img/effects/destructible.jpg',
    description: 'При получении 13 и более урона разрушается',
  },
  {
    effectType: EffectType.ForceBreakingChests,
    name: 'Крепкий взломщик',
    image: 'assets/img/effects/todo.jpg',
    description: '+1 к силовому вскрытию сундуков',
  },
  {
    effectType: EffectType.HealWithAllies,
    name: 'Совместное лечение',
    image: 'assets/img/effects/heal-with-allies.jpg',
    description: 'При лечении союзников лечит себе 4 жизни',
  },
  {
    effectType: EffectType.HideCreature,
    name: 'Существо скрыто',
    image: 'assets/img/effects/todo.jpg',
    description: 'Не может взаимодействовать с противником и стать целью атаки',
  },
  {
    effectType: EffectType.Imbecility,
    name: 'Скудоумие',
    image: 'assets/img/effects/imbecility.jpg',
    description: 'Атакует случайное существо',
  },
  {
    effectType: EffectType.MagicProtection,
    name: 'Магический щит',
    image: 'assets/img/effects/magic-protection.jpg',
    description: 'Защита от магических атак',
  },
  {
    effectType: EffectType.Poison1,
    name: 'Отравление',
    image: 'assets/img/effects/poisoned.jpg',
    description: 'Урон 1',
  },
  {
    effectType: EffectType.Poison2,
    name: 'Отравление',
    image: 'assets/img/effects/poisoned.jpg',
    description: 'Урон 2',
  },
  {
    effectType: EffectType.Poison3,
    name: 'Отравление',
    image: 'assets/img/effects/poisoned.jpg',
    description: 'Урон 3',
  },
  {
    effectType: EffectType.Rage,
    name: 'Ярость',
    image: 'assets/img/effects/rage.jpg',
    description: 'При выпадании 6 во время атаки - удвоение урона.',
  },
  {
    effectType: EffectType.Regeneration1,
    name: 'Регенерация',
    image: 'assets/img/effects/regeneration.jpg',
    description: 'Восстановление 1 за ход',
  },
  {
    effectType: EffectType.Regeneration5,
    name: 'Регенерация',
    image: 'assets/img/effects/regeneration.jpg',
    description: 'Восстановление 5 за ход',
  },
  {
    effectType: EffectType.RebirthSerpent,
    name: 'Возрождение змия',
    image: 'assets/img/effects/todo.jpg',
    description: '',
  },
  {
    effectType: EffectType.ResistPoison1,
    name: 'Иммунитет к яду',
    image: 'assets/img/effects/resist-poison.jpg',
    description: 'Невозможно отравить ядом с уроном 1',
  },
  {
    effectType: EffectType.ResistPoisonAny,
    name: 'Иммунитет к яду',
    image: 'assets/img/effects/resist-poison.jpg',
    description: 'Невозможно отравить',
  },
  {
    effectType: EffectType.ResistStan,
    name: 'Иммунитет к оглушению',
    image: 'assets/img/effects/resist-stan.jpg',
    description: 'Невозможно оглушить',
  },
  {
    effectType: EffectType.ResistStanSpecial,
    name: 'Сопротивление оглушению',
    image: 'assets/img/effects/resist-stan-special.jpg',
    description: 'При оглушении атакой получает 2ой урон, но не оглушается',
  },
  {
    effectType: EffectType.Shield,
    name: 'Щит',
    image: 'assets/img/effects/shield.jpg',
    description: '',
  },
  {
    effectType: EffectType.Slackness,
    name: 'Вялость',
    image: 'assets/img/effects/slackness.jpg',
    description: 'Урон снижается на 2',
  },
  {
    effectType: EffectType.SpecialAttackLegs,
    name: 'Захват',
    image: 'assets/img/effects/special-attack-by-legs.jpg',
    description: 'Игнорирование брони ног. При ударе по ногам противник оглушается на 1 ход.',
  },
  {
    effectType: EffectType.Stan,
    name: 'Оглушение',
    image: 'assets/img/effects/stan.jpg',
    description: 'Пропуск следующего хода.',
  },
  {
    effectType: EffectType.Stan2,
    name: 'Оглушение',
    image: 'assets/img/effects/stan.jpg',
    description: 'Пропуск следующих 2х ходов.',
  },
  {
    effectType: EffectType.Suppression,
    name: 'Подавление',
    image: 'assets/img/effects/suppression.jpg',
    description: 'Получение двойного урона',
  },
  {
    effectType: EffectType.TargetAttackLegs,
    name: 'Прицельная атака',
    image: 'assets/img/effects/target-attack.jpg',
    description: 'Всегда атакует по ногам',
  },
  {
    effectType: EffectType.WounderHeal,
    name: 'Чудотворное лечение',
    image: 'assets/img/effects/wounder-heal.jpg',
    description: 'При выпадании 5 или 6 во время лечения - двойной эффект',
  },
];
