export const MonstersSettings = [
  {
    deep: 1,
    mosterLevel1Min: 1,
    mosterLevel1Max: 1,
    mosterLevel2Min: 0,
    mosterLevel2Max: 0,
    percentBoss: 0,
  },
  {
    deep: 2,
    mosterLevel1Min: 1,
    mosterLevel1Max: 2,
    mosterLevel2Min: 0,
    mosterLevel2Max: 0,
    percentBoss: 0,
  },
  {
    deep: 3,
    mosterLevel1Min: 2,
    mosterLevel1Max: 3,
    mosterLevel2Min: 0,
    mosterLevel2Max: 1,
    percentBoss: 0,
  },
  {
    deep: 4,
    mosterLevel1Min: 1,
    mosterLevel1Max: 2,
    mosterLevel2Min: 1,
    mosterLevel2Max: 1,
    percentBoss: 10,
  },
  {
    deep: 5,
    mosterLevel1Min: 2,
    mosterLevel1Max: 2,
    mosterLevel2Min: 1,
    mosterLevel2Max: 1,
    percentBoss: 10,
  },
  {
    deep: 6,
    mosterLevel1Min: 2,
    mosterLevel1Max: 3,
    mosterLevel2Min: 1,
    mosterLevel2Max: 2,
    percentBoss: 10,
  },
  {
    deep: 7,
    mosterLevel1Min: 1,
    mosterLevel1Max: 1,
    mosterLevel2Min: 2,
    mosterLevel2Max: 2,
    percentBoss: 33,
  },
  {
    deep: 8,
    mosterLevel1Min: 1,
    mosterLevel1Max: 2,
    mosterLevel2Min: 2,
    mosterLevel2Max: 2,
    percentBoss: 33,
  },
  {
    deep: 9,
    mosterLevel1Min: 2,
    mosterLevel1Max: 3,
    mosterLevel2Min: 2,
    mosterLevel2Max: 3,
    percentBoss: 33,
  },
];
